name: Push Desktop File to GitHub
on: [push]
   
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        
      - name: Copy Desktop File
        run: |
             cp C:/Users/ACER/Desktop/prime.java C:/Users/ACER/new-git
             git remote add origin https://github.com/steja6872/new-git.git
             git add prime.java
             git commit -m "Add prime.java file"
             git push -u origin main
      
      






