name: Push Desktop File to GitHub
on: [push]
   
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        
      - name: Copy Desktop File
        run: cp C:/Users/ACER/Desktop/prime.java C:/Users/ACER/new-git  
          
      - name: Add changes
        run: |
            cd C:/Users/ACER/new-git
            pwd
            git status
         
        #   git add prime.java

   #   - name: Commit changes
    #    run: git commit -m "Add Java file"

     # - name: Push changes to GitHub
      #  uses: ad-m/github-push-action@master
       # with:
        #  github_token: ${{ secrets.GIT_TOKEN }}
         # branch: main     
      
             
      
      






