name: Push Desktop File to GitHub
on: [push]
   
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        
      - name: Copy Desktop File
        run: cp C:/Users/ACER/Desktop/prime.java C:/Users/ACER/new-git
      
      - name: Check git version
        run: git --version
        
      - name: Configure Git
        run: |
             git config --global user.email "steja6872@gmail.com"
             git config --global user.name "steja6872"

        
      - name: Commit Changes
        run: |
             git init
             git remote add origin https://github.com/steja6872/new-git.git
             git add .
             git commit -m "Add desktop file"
             git push -u origin main
          
      - name: Push Changes
        uses: ad-m/github-push-action@master
