name: Push Desktop File to GitHub
on: [push]
   
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        
      - name: Copy Desktop File
        run: cp C:/Users/ACER/Desktop/prime.java C:/Users/ACER/new-git
      
      - name: Set up Git
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Configure Git
        run: |
          git config --global user.name "steja6872"
          git config --global user.email "steja6872@gmail.com"
      
      - name: Commit changes
        run: |
          git add .
          git commit -m "Add prime.java file"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        






